[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
user=nextjs

[program:main_app]
command=node server.js
directory=/app
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/app/logs/main_app.log
stdout_logfile_maxbytes=50MB
stopasgroup=true
killasgroup=true
user=nextjs

[program:app_worker]
command=node /app/worker/workers/index.js
directory=/app
autostart=true
autorestart=true
startretries=5
redirect_stderr=true
stdout_logfile=/app/logs/app_worker.log
stdout_logfile_maxbytes=50MB
stopasgroup=true
killasgroup=true
user=nextjs
